Traceback (most recent call last):
  File "/home/iridium/anaconda3/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/iridium/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/iridium/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/iridium/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/iridium/anaconda3/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/home/iridium/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/iridium/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/iridium/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
(pre_tf_res.loc[get_skidl_spice_ref(vs_8)]==post_tf_res.loc[get_skidl_spice_ref(vs_8)]).all()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-11-ed8ea9e6167c>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;34m([0m[0mpre_tf_res[0m[0;34m.[0m[0mloc[0m[0;34m[[0m[0mget_skidl_spice_ref[0m[0;34m([0m[0mvs_8[0m[0;34m)[0m[0;34m][0m[0;34m==[0m[0mpost_tf_res[0m[0;34m.[0m[0mloc[0m[0;34m[[0m[0mget_skidl_spice_ref[0m[0;34m([0m[0mvs_8[0m[0;34m)[0m[0;34m][0m[0;34m)[0m[0;34m.[0m[0mall[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m<ipython-input-6-8d6dbea5f147>[0m in [0;36mget_skidl_spice_ref[0;34m(skidle_element)[0m
[1;32m     16[0m [0;34m[0m[0m
[1;32m     17[0m     """
[0;32m---> 18[0;31m     [0;32massert[0m [0mrepr[0m[0;34m([0m[0mtype[0m[0;34m([0m[0mskidle_element[0m[0;34m)[0m[0;34m)[0m[0;34m==[0m[0;34m"<class 'skidl.Part.Part'>"[0m[0;34m,[0m [0;34m'`skidle_element` must be a SKiDl part'[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     19[0m [0;34m[0m[0m
[1;32m     20[0m     [0;32mif[0m [0mskidle_element[0m[0;34m.[0m[0mref_prefix[0m[0;34m!=[0m[0mskidle_element[0m[0;34m.[0m[0mref[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mAssertionError[0m: `skidle_element` must be a SKiDl part
AssertionError: `skidle_element` must be a SKiDl part

